# -*- coding: utf-8 -*-
"""parse_gtex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ERX73eGvYZGHO6mGhRv7AExMzMVYfNkR

Some print statements from the original file have been removed for readability.
"""

import numpy as np
import pandas as pd

# note: large size of rna seq file required downloading and unzipping to local 
# system first

# load rna-seq data (gene counts, one gene/row and one sample/col)
df = pd.read_csv('GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.txt', header=2, sep='\t')

# load sample annotations (one sample/row and one attribute/col)
annotated_df = pd.read_csv('https://storage.googleapis.com/gtex_analysis_v8/annotations/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt', sep='\t')
annotated_df.head(n=3)

# get list of all unique tissues from sample annotations
tissues = pd.unique(annotated_df['SMTS'])

# build subset of rna-seq data for each tissue
tissue_sep = {}
for t in tissues:
  tissue_sep[t] = []
  for row in annotated_df.itertuples(index=False):
    if row.SMTS == t:
      tissue_sep[t].append(row.SAMPID)

# create separate text files for rna-seq data from each tissue
for t in tissue_sep:
  outname = t.replace(" ", "") + "_counts.tsv"
  print(outname)
  temp_df = df.filter(items=['Name', 'Description'] + tissue_sep[t])
  temp_df.to_csv(outname, sep='\t')
